spring.application.name=A3nguyenphamhoangminh_se18D04
# Server Port
server.port=8080

# Database Connection (Thay doi ten database theo yeu cau: A3 StudentName_ClassCode)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=A3nguyenphamhoangminh_se180D04;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA (Tu dong tao bang dua tren Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Default Staff Account (Lay tu file nay theo yeu cau cua de bai)
staff.account.email=admin@fuminhotel.com
staff.account.password=admin123